apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openid-app
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    path: rhsso-operator/overlays/default
    repoURL: https://github.com/pittar/rhsso
    targetRevision: master
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
